name: Robot Framework Reporter Demo

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      uses: joonvena/robotframework-docker-action@v1.0
      with:
        robot_tests_dir: test
    - name: Store test report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: reports
        path: reports


